services:

  # Contenedor datawarehouse
  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl_network

  # Base de datos interna de Airflow
  postgres_airflow:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_DB: airflow_db
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow123
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  # Servidor web Airflow
  airflow_webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres_airflow/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_clave_secreta_123
      DB_HOST: ecommerce_postgres
      DB_PORT: "5432"
      DB_NAME: ecommerce_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DATA_RAW_PATH: /opt/airflow/data/raw
      DATA_PROCESSED_PATH: /opt/airflow/data/processed
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8081:8080"
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --firstname Admin --lastname ETL --role Admin --email admin@ecommerce.com --password admin123 &&
               airflow webserver"
    networks:
      - etl_network

  # Scheduler Airflow
  airflow_scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres_airflow
      - airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres_airflow/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_clave_secreta_123
      DB_HOST: ecommerce_postgres
      DB_PORT: "5432"
      DB_NAME: ecommerce_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DATA_RAW_PATH: /opt/airflow/data/raw
      DATA_PROCESSED_PATH: /opt/airflow/data/processed
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - airflow_logs:/opt/airflow/logs
    command: scheduler
    networks:
      - etl_network

  # Apache Superset
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: ecommerce_superset
    restart: always
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: superset_clave_secreta_123
    depends_on:
      - postgres
    networks:
      - etl_network
networks:
  etl_network:
    driver: bridge
volumes:
  postgres_data:
  airflow_postgres_data:
  airflow_logs:

